name: 'Return Delta'
description: 'Return Delta changes'
inputs:
  commit-ref:  # COMMIT ID
    description: 'Commit Id'
    required: true
outputs:
  random-number:
    description: "Return filename"
    value: ${{ steps.random-number-generator.outputs.random-number }}
runs:
  using: "composite"
  steps:
    - name: Get Delta file
      run: |
        curl -L \
        -H "Accept: application/vnd.github+json" \
        -H "Authorization: Bearer <YOUR-TOKEN>" \
        -H "X-GitHub-Api-Version: 2022-11-28" \
        https://api.github.com/repos/rakhisingh7/lwc-recipes/commits/${{inputs.commit-ref}} > commit.json
      shell: bash
      #env:
       # COMMIT: ${{inputs.commit-ref}}

    - name: Random Number Generator
      id: random-number-generator
      run: echo "random-number=$(echo $RANDOM)" >> $GITHUB_OUTPUT
      shell: bash


