name: Validate Deployment
on: 
  workflow_dispatch:

  push: 
    branches:
      - main
      - dev
  
jobs:
  pmd-scan:
    uses: ./.githubs/workflows/pmd.yml

  check-status:
    needs: pmd-scan
    runs-on: ubuntu-latest
    steps:
      - name: Print PMD scan status
        run: echo "${{ needs.pmd-scan.outputs.pmd_scan_status }}"
  
