name: Dry-run
on: 
  workflow_dispatch:

  push: 
    branches:
      - main
      - dev
  
jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
       - name: Checkout code
         uses: actions/checkout@v4
         with:
           ref: dev
  
  pmd-scan:
    needs: checkout
    uses: ./.github/workflows/pmd.yml

  check-status:
    needs: pmd-scan
    runs-on: ubuntu-latest
    steps:
      - name: Print PMD scan status
        run: echo "abc"
        #run: echo "${{ needs.pmd-scan.outputs.pmd_scan_status }}"
  
