name: PMD Scan
on: 
  workflow_call:
    outputs:
      pmd_scan_status:
        description: This is the status of pmd scan result
        value: ${{ jobs.pmd.outputs.fail-pmd-result }}
jobs:
  pmd:
    runs-on: ubuntu-latest
    outputs:
      fail-pmd-result: ${{ steps.result.outputs.pmd-result }}
    steps:
      - id: result
        run: echo "pmd-result=Success" >> $GITHUB_OUTPUT