name: Reusable Deployment
on: 
  workflow_dispatch:

  push: 
    branches:
      - main
      - dev
jobs:
  checkout:
    runs-on: ubuntu-latest
    #container:
    #  image: salesforce/cli:latest-rc-slim
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: dev

  call-pmd-scan:
    uses: ./github/workflows/pmd.yml

  display-reusable-output:
    needs: pmd-scan
    runs-on: ubuntu-latest
    steps:
      - name: Print PMD scan status
        run: echo "${{ needs.pmd-scan.outputs.pmd_scan_status }}"
  
