name: Validate Deployment
on: 
  workflow_dispatch:

  push: 
    branches:
      - main
      - dev
jobs:
  pmd-scan:
    runs-on: ubuntu-latest
    #container:
    #  image: salesforce/cli:latest-rc-slim
  #outputs: 
  #    report: ${{ steps.result.outputs.pmd_scan_status }}"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: dev
      - name: PMD scan
        id: result
        run: echo " pmd_scan_status = first yml " >> $GITHUB_OUTPUT
        #uses: ./github/workflows/pmd.yml
      - name: Print PMD scan status
        run: echo "${{ steps.result.pmd_scan_status }}"

