name: Validate Deployment
on: 
  workflow_dispatch:
  push: 
    branches:
      - main
      - dev
jobs:
  pmd-scan:
    runs-on: ubuntu-latest
    #container:
    #  image: salesforce/cli:latest-rc-slim
    steps:
      - name: Checkout code
        run: actions/checkout@v4
        with:
          ref: dev
      - name: PMD scan
        id: result
        run: echo " pmd_scan_status = 'first yml' " >> GITHUB-OUTPUT
        #uses: ./github/workflows/pmd.yml
      - name: Print PMD scan status
        run: echo "PMD Scan status ${{ steps.result.outputs.pmd_scan_status }}"

